### ISSUE TITLE
Error: gzip: stdin: invalid compressed data--crc error

### ISSUE THREAD

**Issue by ucerd** [sdsc/pgi-roll#1]
I have placed same version (18.10) as well as updated version (19.10) in src/pgi directory (did modification in version.mk file accordingly) but for both cases I am getting this error

) > DESCRIPTION
::: Downloading http://forge.sdsc.edu/triton/pgi/src/pgi/pgilinux-2018-1810-x86-64.tar.gz :::
::: pgilinux-2018-1810-x86-64.tar.gz exists. Skipping... :::
::: Unbundling pgilinux-2018-1810-x86-64.tar.gz :::

gzip: stdin: invalid compressed data--crc error
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
make[3]: *** [pgilinux-2018-1810-x86-64] Error 2
make[3]: Leaving directory `/state/partition1/site-roll/rocks/src/pgi-roll-master/src/pgi'

**Comment by tcooper** [comment]
A few possibilities here...

- Are your downloaded PGI tarballs valid? Use tar command with `-t` option to verify.
- Do you have enough disk space available to unpack the tarball?
- Do the file sizes and Git blob SHAs match those in the binary_hashes for each of the tarballs.

**Comment by ucerd** [comment]
Thanks tcooper
There was error in tar.gz file. The above issue has been solved.
