### ISSUE TITLE
PGI compiler Issue on Rock Cluster frontend node

### ISSUE THREAD

**Issue by usmanfarooq948** [sdsc/pgi-roll#3]
Sorry i am new to Rock Distribution. How a user can compile his application using PGI compiler. As i Know Front-end node only manages software packages on cluster as well as the submitted jobs and compute-end provide the processing power.

**Comment by tcooper** [comment]
This question is appropriate for the Rocks Mailing List which you can access [here](http://www.rocksclusters.org/docs.html).
